#ifndef GLOBALS_H
#define GLOBALS_H



enum StateType {SYSTEM_INITIALIZATION, RUN_GENERATOR, EMPTY_GEN_FOR_SET, EMPTY_GEN, WAIT, STOP_GEN, CUBE_STATE_INIT,
                INITIATE_SENSOR_READING, GET_SENSOR_READING,
                //CUBE_STATE_WRITING, CUBE_STATE_CHANGE, COMMUNICATE_WITH_SOLVER, MANIPULATION_SEQ_TRANSLATION,
            STATES_NUMBER };

enum GeneratorType {ECP_GEN_TEACH_IN, ECP_GEN_NEWSMOOTH, ECP_GEN_WEIGHT_MEASURE, ECP_GEN_TRANSPARENT, ECP_GEN_TFF_NOSE_RUN,
     ECP_GEN_BIAS_EDP_FORCE, ECP_GEN_TFF_RUBIK_GRAB, ECP_GEN_TFF_RUBIK_FACE_ROTATE, ECP_ST_GRIPPER_OPENING,
                GENERATORS_NUMBER};

enum Robot {ROBOT_UNDEFINED, ROBOT_IRP6OT_M, ROBOT_IRP6P_M, ROBOT_FESTIVAL, ROBOT_CONVEYOR, ROBOT_SPEAKER,
            ROBOT_IRP6_MECHATRONIKA, ROBOT_ELECTRON, ROBOT_HAND, ROBOT_SPEECHRECOGNITION,
      ROBOTS_NUMBER};

enum Sensor {SENSOR_CAMERA_ON_TRACK, SENSOR_CAMERA_SA,
        SENSORS_NUMBER};

enum CoordType {ECP_INVALID_END_EFFECTOR, ECP_XYZ_ANGLE_AXIS, ECP_XYZ_EULER_ZYZ, ECP_JOINT, ECP_MOTOR, ECP_PF_VELOCITY,
            COORDTYPES_NUMBER};

enum MotionType {ABSOLUTE, RELATIVE,
             MOTIONTYPES_NUMBER};

enum Transmitter {TRANSMITTER_RC_WINDOWS,
            TRANSMITTERS_NUMBER};




#endif // GLOBALS_H
